# Generated by Django 5.1.7 on 2025-04-12 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_manufacturer_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailoutreach',
            unique_together={('user', 'manufacturer')},
        ),
    ]
